# Generated by Django 2.2.5 on 2020-05-14 14:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmodel',
            name='content',
            field=models.TextField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boardmodel',
            name='good',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boardmodel',
            name='read',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
